databases:
  - name: onboarding-db
    databaseName: onboarding
    user: onboarding_user
    plan: free

services:
  - type: web
    name: onboarding-system
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm run db:seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: onboarding-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://onboarding-system.onrender.com 